import os

from dotenv import load_dotenv

from paths import PARENT_DIR

import sys
from pathlib import Path
sys.path.append(str(Path(__file__).resolve().parent.parent))


from src.feature_store_api import FeatureGroupConfig, FeatureViewConfig

# load key-value pairs from .env file located in the parent directory
load_dotenv(PARENT_DIR / '.env')

try:
    HOPSWORKS_PROJECT_NAME = os.environ['HOPSWORKS_PROJECT_NAME']
    HOPSWORKS_API_KEY = os.environ['HOPSWORKS_API_KEY']
except:
    raise Exception(
        'Create an .env file on the project root with the HOPSWORKS_PROJECT_NAME and HOPSWORKS_API_KEY'
    )

# remove FEATURE_GROUP_NAME and FEATURE_GROUP_VERSION, and use FEATURE_GROUP_METADATA instead
FEATURE_GROUP_NAME = 'time_series_hourly_feature_group'
FEATURE_GROUP_VERSION = 1
# defimos metadata del feature group
FEATURE_GROUP_METADATA = FeatureGroupConfig(
    name=FEATURE_GROUP_NAME,
    version=FEATURE_GROUP_VERSION,
    description='Feature group with hourly time-series data of historical taxi rides',
    primary_key=['pickup_location_id', 'pickup_ts'],
    event_time='pickup_ts',
    online_enabled=True,
)


FEATURE_VIEW_NAME = 'time_series_hourly_feature_view'
FEATURE_VIEW_VERSION = 1
# definimos metadata del feature view
FEATURE_VIEW_METADATA = FeatureViewConfig(
    name=FEATURE_VIEW_NAME,
    version=FEATURE_VIEW_VERSION,
    feature_group=FEATURE_GROUP_METADATA,
)

MODEL_NAME = 'taxi_demand_predictor_next_hour'
MODEL_VERSION = 4

FEATURE_GROUP_PREDICTIONS_METADATA = FeatureGroupConfig(
    name='taxi_demand_predictions',  # ← corregido aquí
    version=1,
    description='Predictions generated by our production model',
    primary_key=['pickup_location_id', 'pickup_ts'],
    event_time='pickup_ts',
)

FEATURE_VIEW_PREDICTIONS_METADATA = FeatureViewConfig(
    name='taxi_demand_predictions_view',  # ← también corregido aquí
    version=1,
    feature_group=FEATURE_GROUP_PREDICTIONS_METADATA,
)

# MONITORING_FV_NAME = 'monitoring_feature_view'
# MONITORING_FV_VERSION = 1

# # number of historical values our model needs to generate predictions
N_FEATURES = 24

# # number of iterations we want Optuna to pefrom to find the best hyperparameters
# N_HYPERPARAMETER_SEARCH_TRIALS = 1

# # maximum Mean Absolute Error we allow our production model to have
# MAX_MAE = 30.0